### PR TITLE
US171Task202 Test HODForm w/ basic pattern for form testing.

### PR DESCRIPTION
**Pull request by Tengelma**
This establishes a pattern for the testing of forms & does a little more setup for the testing environment as a whole.

The HODForm contains 5 tests --
- a check to ensure that, when mounted, the form has the correct default model
- a check to ensure that whenever the selected model changes, the parameters also change
- a check to ensure that whenever the selected model changes, the correct fields are rendered
- a check to ensure that whenever the selected model changes, the 'onChange' event is emitted
- a check to ensure that whenever the value of the model parameters change, the 'onChange' event is emitted

Includes:
client/jest.config.js update
client/\__tests__/HODForm.spec.js
client/\__tests__/setup.js

Developer Checklist:
- [X] The code follows the Quality Policy file on Google Drive
- [X] My code has been developer-tested and includes unit tests
- [X] I have considered proper use of exceptions
- [X] I have eliminated IDE warnings

### CODE REVIEW

**Review by aneuhold — COMMENTED** [review]
This looks great! The only question that seems worth asking is about the code coverage. Whenever checking out the code coverage it shows the below:

Code coverage

Does it show something different on another person's machine?

**Comment by Tengelma** [comment]
> This looks great! The only question that seems worth asking is about the code coverage. Whenever checking out the code coverage it shows the below:
> 
> Code coverage
> 
> Does it show something different on another person's machine?

Running it again I had the same issue. Resolved it in recent commit, though!
image

**Review by aneuhold — APPROVED** [review]
Looks great!

**Review by vperuzzi — APPROVED** [review]

**Comment by aneuhold** [comment]
It looks like it is failing some linting tests on the front-end.

**Comment by Tengelma** [comment]
Going ahead and merging because linting has been resolved and it has two approvals.

**Pull request merged**
