### PR TITLE
Hm88 scrollable menu and auto snap

### PR DESCRIPTION
**Pull request by aschnapp**
### Overview
A drawer component and a place to put the forms for /create route (and potentially for /update route) 
go to localhost:8080/create to view the changes

### Includes:
see files changed tab for changes

### Developer Checklist:
- [x] The code follows the `QualityPolicy.md` file
~~- [ ] My code has been developer-tested and includes unit tests~~
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

###Notes:
I remember the tests are scheduled for next week. Does no include any tests in this pr.

### Refs:
- [Ticket](https://the-halo-mod.atlassian.net/browse/HM-88)

### CODE REVIEW

**Review by aneuhold — CHANGES_REQUESTED** [review]
Just tried to run this locally but there isn't an option to go to the new create page and when trying to go to it manually, it seems to error out like so:

Error

Any suggestions on how to see this in action?

**Comment by aneuhold** [comment]
Never mind. Got it to work by putting in the right method of going to an endpoint on the site. Next time it would be nice to have some short instructions on how to view the changes that were made though. 

@aschnapp is `Create.vue` going to end up in the final app? How is this going to integrate with the home page?

**Comment by aschnapp** [comment]
> Never mind. Got it to work by putting in the right method of going to an endpoint on the site. Next time it would be nice to have some short instructions on how to view the changes that were made though.
> 
> @aschnapp is `Create.vue` going to end up in the final app? How is this going to integrate with the home page?
> 
> This looks great by the way though. Just what we were looking for. As long as this is integrated into the home page we are golden.

We dont have a task for the home page buttons to create and update models for this sprint. It can be part of this [ticket](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-106) though

**Review by aneuhold — APPROVED** [review]
Oh. I think I see what you are getting at here with the creating of models. Sounds good!

**Review by vperuzzi — APPROVED** [review]

**Pull request merged**
