### PR TITLE
US188 T194 Fix Model Name

### PR DESCRIPTION
**Pull request by aneuhold**
### Overview
This fixes an issue where the model name wasn't syncing when "edit" was pressed. It also cleans up some of the code. 

Also trying to figure out how to do tests with this. It might be something that is handled by the store testing though. 

### Includes:
- client/src/components/ModelMetadataForm.vue 
- client/src/components/Models/index.vue 
- client/src/views/Create.vue 

### Developer Checklist:
- [x] The code follows the Quality Policy file on Google Drive
- [ ] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

### Refs:
- [Task 194](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-194)

### CODE REVIEW

**Review by aschnapp — CHANGES_REQUESTED** [review]
It creates a new model when you hit save after editing when the model is still loading. Do you think we should disable the edit, delete, copy, when it is loading?

**Comment by aneuhold** [comment]
> It creates a new model when you hit save after editing when the model is still loading. Do you think we should disable the edit, delete, copy, when it is loading?

That is a great idea :) Working on getting that added in.

**Comment by aneuhold** [comment]
@aschnapp Now the buttons are disabled when a model is loading. 😄

**Review by aschnapp — APPROVED** [review]

**Comment by aschnapp** [comment]
Approved!

**Comment by Tengelma** [comment]
Looks good to me!

**Review by Tengelma — APPROVED** [review]

**Pull request merged**
