### PR TITLE
US92 halo model form

### PR DESCRIPTION
**Pull request by dblevin1**
### Overview
Quick fix so the HaloModel form returns the correct model with only the parameter values.

### Includes:
- client/src/components/HaloModelForm.vue
- client/src/constants/backend_constants.js

### Developer Checklist:
- [x] The code follows the Quality Policy file on Google Drive
- [ ] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

### CODE REVIEW

**Review by aschnapp — APPROVED** [review]

**Review by aschnapp — CHANGES_REQUESTED** [review]
It's still failing

**Comment by Tengelma** [comment]
> It's still failing

The issue is with the 'range' fields -- these need to have a min and a max and those need to correspond to something in the payload. I just made a commit on your US92 branch that fixes it I think but it uses two separate fields instead of 1 for both of the ranges & also doesn't account for the log scale.

Just as an example, the field from forms.py I listed below corresponds to 'rmin' and 'rmax' in the payload so if you have a range slider it needs to have two ends. The reverse of that 'np.log10' call also needs to be done on it before its actually sent in the payload. We can probably send this through to get dev back in working order but this functionality should probably be handled at some point :)

image

**Review by aschnapp — APPROVED** [review]
Working now!

**Review by aneuhold — APPROVED** [review]
Looks good!

**Comment by aschnapp** [comment]
@dblevin1 can you look at this pr before you merge? I moved the data to backend constant.
https://github.com/steven-murray/TheHaloMod-SPA/pull/36

**Pull request merged**
