### PR TITLE
US167 Flask Session Logic and Testing

### PR DESCRIPTION
**Pull request by Tengelma**
Overview
Overhauls backend to support sessions, updates documentation & adds tests for new endpoints.

You will need to install redis on your machine with
```
sudo apt update
sudo apt install redis-server
```
for the server to run.

Includes: 
Check Files Changed

Developer Checklist:
- [X] The code follows the Quality Policy file on Google Drive
N/A My code has been developer-tested and includes unit tests
- [X] I have considered proper use of exceptions
- [X] I have eliminated IDE warnings

### CODE REVIEW

**Comment by aneuhold** [comment]
Does this mean that Redis will need to be bundled up to work with TravisCI somehow? Or at least scripted to install and run from `run.sh`? Otherwise it sounds like the redis server will need to be hosted somewhere else.

**Comment by Tengelma** [comment]
> Does this mean that Redis will need to be bundled up to work with TravisCI somehow? Or at least scripted to install and run from `run.sh`? Otherwise it sounds like the redis server will need to be hosted somewhere else.

I handled this in the .travis.yml file -- pretty simple addition to add a redis service. Build succeeds / finishes it because of it :)

**Review by aneuhold — APPROVED** [review]
Runs locally, tests pass, and file changes look good.

**Review by aschnapp — APPROVED** [review]
Going to approve it, but I can't tell the difference in speedup.. idk why

**Pull request merged**
